### ISSUE TITLE
ci: add tests to travis-ci

### ISSUE THREAD

**Issue by jlefevre** [uccross/skyhookdb-ceph#9] opened 2018-07-20 21:50 UTC
Let's add the below data and query tests to travis-ci for an OSD=3 vstart cluster.  The dataset has 1M rows in 10 objects (135MB) and is located here:
skyhook1.soe/ucsc.edu:/mnt/storage1/tpchdata/nrows1Mnobjs10/obj*.bin
The expected output for each query is noted inline.  
```

cd [build]

# CREATE THE STORAGE POOL
bin/rados mkpool tpch

# STORE THE DATA
PATH=$PATH:bin ../src/progly/rados-store-glob.sh tpch  /mnt/storage1/tpchdata/nrows1Mnobjs10/obj*.bin

# TEST QUERY B - NO CLS (returns all rows to client)
# selectivity=1%
# expect “total result row count: 10172 / 1000000; nrows_processed=1000000”
bin/run-query --num-objs 10 --pool tpch --wthreads 10 --qdepth 10 --quiet --extended-price 91400.0 --query b

# TEST QUERY B - NO CLS (returns all rows to client)
# selectivity=100%
# expect “total result row count: 1000000 / 1000000; nrows_processed=1000000”
bin/run-query --num-objs 10 --pool tpch --wthreads 10 --qdepth 10 --quiet --extended-price 1.0 --query b

# TEST QUERY D - NO CLS (returns all rows to client)
# selectivity=single row
# expect “total result row count: 1 / 1000000; nrows_processed=1000000”
bin/run-query --num-objs 10 --pool tpch --wthreads 10 --qdepth 10 --quiet --query d --order-key 5 --line-number 3

# TEST QUERY B - WITH CLS (only returns matching rows to client)
# selectivity=1%
# expect “total result row count: 10172 / 10172; nrows_processed=1000000”
bin/run-query --num-objs 10 --pool tpch --wthreads 10 --qdepth 10 --quiet --extended-price 91400.0 --query b --use-cls

# TEST QUERY D - WITH CLS (only returns matching rows to client)
# selectivity=single row
# expect “total result row count: 1 / 1; nrows_processed=1000000”
bin/run-query --num-objs 10 --pool tpch --wthreads 10 --qdepth 10 --quiet --query d --order-key 5 --line-number 3 --use-cls

# TEST QUERY D - WITH CLS BEFORE BUILD INDEX
# selectivity=single row
# expect total result row count: 0 / 0; nrows_processed=0”
bin/run-query --num-objs 10 --pool tpch --wthreads 10 --qdepth 10 --quiet --query d --order-key 5 --line-number 3 --use-cls --use-index

# BUILD THE INDEX for each obj
 bin/run-query --num-objs 10 --pool tpch --wthreads 10 --qdepth 10 --quiet --query d  --build-index

# TEST QUERY D - WITH CLS AFTER BUILD INDEX
# selectivity=single row
# expect “total result row count: 1 / 1; nrows_processed=1000000”
bin/run-query --num-objs 10 --pool tpch --wthreads 10 --qdepth 10 --quiet --query d --order-key 5 --line-number 3 --use-cls --use-index

# TEST SIMPLE FASTPATH QUERY WITH CLS 
# selectivity=100% (select * from T)
# expect “total result row count: 1000000 / 1000000; nrows_processed=1000000"
run-query --num-objs 10 --pool tpch --wthreads 10 --qdepth 10 --quiet --query fastpath --use-cls
```

**Comment by michaelsevilla** [comment] 2018-07-24 19:56
There are two issues with this:
- Disk space: Travis only has 30GB on each node and to run `vstart`, we need to run out of a directory with binaries compiled. Compiling all of Ceph usually takes up about 40Gb of space. I'll look at what a minimum build takes (i.e., just compile `osd` and `mon`) and see if I can launch a `vstart` cluster from that.
- Time: Travis only allows tests up to 50 minutes, so compiling the new binaries and then running the tests might take too much time. Just compiling the OSD, Objecter, CLS classes, and librados takes almost 45 minutes. I'll look at precompiling binaries, pulling them, and then layering new changes on them to see if the queries still run.

**Comment by michaelsevilla** [comment] 2018-07-27 00:00
After looking at this for a bit, the best course of action appears to be sharing binaries across Travis stages with DockerHub, as described [here](https://docs.travis-ci.com/user/build-stages/share-docker-image/). For our code base, that would mean:

**Stage 1**: Compile Code and Build Image
1. Build binaries necessary for `vstart.sh`. This appears to be just `ceph-osd`, `osdc`, `librados`, `cls_tabular`, `ceph-authtool`, `ceph-mon`, `monmaptool`, and `crushtool`. We also need to build Python libraries with `cd src/pybind/ && make`.
2. Delete the `/libs` and `/bin` folders because these binaries can quickly be re-generated.
3. Copy the `/src` folder into a "binaries" container and commit.
4. Push the "binaries" container to DockerHub. 

**Stage 2**: Execute Data and Query Tests
1. Pull "binaries" container from DockerHub.
2. Run the `make` command again (which executes in ~30 seconds) to populate the `/libs` and `/bin` folders.
3. Run `MON=1 MDS=0 ../src/vstart.sh -n -l`.
3. Run the query tests.

The "binaries" container should only be 3.1GB.

**Comment by michaelsevilla** [comment] 2018-07-28 01:18
Ran an experiment to figure out the size and time requirements of the build and deploy scripts. The output of the job is [here](https://travis-ci.com/uccross/skyhookdb-ceph/builds/80271206). Confirmed that the following takes too long:

```bash
$ make -j2 ceph-osd osdc librados cls_tabular ceph-authtool ceph-mon monmaptool crushtool
$ cd /ceph/build/src/pybind && make -j2
```

But also showed that there should be enough space on the node:

```bash
$ df -h
[... snip ...]
/dev/sda1        30G   18G   12G  59% /
[... snip ...]
```

So unless the `pybind` binaries and libraries are bigger than 12GB we should be good. Next I'm going to look at building ceph binaries, packaging them into a container, pushing to DockerHub (**Stage 1**), then pulling the image, compiling `pybind` binaries and libraries, pushing to DockerHub again (**Stage 2**), and then pulling the image, running vstart, and doing the integration tests.

**Comment by michaelsevilla** [comment] 2018-07-28 17:34
Unfortunately, compiling and packaging up binaries in a Docker container takes too long (almost 49 minutes, according to a recent experiment [here](https://travis-ci.com/uccross/skyhookdb-ceph/builds/80288100)). So we need to mitigate this with DockerHub. Splitting into more stages increases load on DockerHub but this shouldn't be too bad if we layer properly.

**Comment by noahdesu** [comment] 2018-07-28 18:16
You could avoid building ceph by using the normal ceph packages and building the plugin separately. We do this w zlog and the build just takes a few min

**Comment by michaelsevilla** [comment] 2018-07-28 19:46
You mean how you just build CLS ([link](https://github.com/cruzdb/zlog/blob/master/docker/ceph-plugin/entrypoint.sh#L17))? In Skyhook, don't we need to rebuild the OSD:

```bash
$ git diff --name-only 98a87fa | grep "osd\/\|osdc\/\|librados"
src/include/rados/librados.hpp
src/librados/IoCtxImpl.cc
src/librados/IoCtxImpl.h
src/librados/librados.cc
src/osd/PrimaryLogPG.cc
src/osdc/Objecter.cc
src/osdc/Objecter.h
```

The part that takes a long time is:
```bash
$ make ceph-osd osdc librados cls_tabular 
```

Thoughts?

**Comment by noahdesu** [comment] 2018-07-28 20:59
If your goal is "run ceph with the skyhook cls plugin" then you don't need to build ceph. the following two option _should_ work:

just run make cls_tabular, then copy the libcls_tabular.so into /usr/lib/rados-classes/ on any node running an OSD. The actual OSD can be installed with pre-built packages (e.g. apt-get install ceph).

but maybe I'm misunderstanding what your goal is.

**Comment by noahdesu** [comment] 2018-07-28 22:32
For the tests that I'm aware of that are related to skyhook, the only
changes to ceph should be in the cls plugin. The Ceph tree we use for
skyhook (IIRC) started off as a tree where I was hacking on other random
things. That is also a good reason to move to Luminous or Mimic---to start
off with a clean tree. Maybe you could post the diff that touches
directories other than cls? That'd give a clue as to what the changes are.

**Comment by jlefevre** [comment] 2018-07-31 22:35
I modified the above expect output string format from:
- expect “total result row count: X / Y" to:
- expect “total result row count: X / Y; nrows_processed=Z"

to match the new output of skyhook-luminous branch.
Using these strings is fragile, but is still useful for now as we move to a new data layout, thanks.

**Comment by jlefevre** [comment] 2018-08-07 03:02
Added 2 skyhookdb flatbuf layout queries to original post above for some functionality added with [commit ](https://github.com/uccross/skyhookdb-ceph/commit/ae44b8eeb98f0b6c7d69821257350ba59f544991)

**Comment by michaelsevilla** [comment] 2018-09-03 17:50
Removing flatbuffer queries. I want to close this and right now it's a moving target. Moved queries to #13.

**Comment by michaelsevilla** [comment] 2018-09-14 03:50
Done with #14.

**Closed by michaelsevilla** 2018-09-14 03:50 UTC
